(ns reagent.react-native
  (:require [react-native :as rn]
            [reagent.core :as r]))

(def accessibility-info (r/adapt-react-class rn/AccessibilityInfo))
(def activity-indicator (r/adapt-react-class rn/ActivityIndicator))
(def button (r/adapt-react-class rn/Button))
(def checkbox (r/adapt-react-class rn/Checkbox))
(def flat-list (r/adapt-react-class rn/FlatList))
(def image (r/adapt-react-class rn/Image))
(def image-background (r/adapt-react-class rn/ImageBackground))
(def input-accessory-view (r/adapt-react-class rn/InputAccessoryView))
(def keyboard-avoiding-view (r/adapt-react-class rn/KeyboardAvoidingView))
(def modal (r/adapt-react-class rn/Modal))
(def picker (r/adapt-react-class rn/Picker))
(def pressable (r/adapt-react-class rn/Pressable))
;;(def navigation-container (r/adapt-react-class rn/NavigationContainer))
(def refresh-control (r/adapt-react-class rn/RefreshControl))
(def safe-area-view (r/adapt-react-class rn/SafeAreaView))
;;(def stack (r/adapt-react-class rn/Stack))
(def scroll-view (r/adapt-react-class rn/ScrollView))
(def section-list (r/adapt-react-class rn/SectionList))
(def status-bar (r/adapt-react-class rn/StatusBar))
(def slider (r/adapt-react-class rn/Slider))
(def switch (r/adapt-react-class rn/Switch))
(def refresh-control (r/adapt-react-class rn/RefreshControl))
(def status-bar (r/adapt-react-class rn/StatusBar))
(def text (r/adapt-react-class rn/Text))
(def text-input (r/adapt-react-class rn/TextInput))
(def touchable (r/adapt-react-class rn/Touchable))
(def touchable-highlight (r/adapt-react-class rn/TouchableHighlight))
(def touchable-native-feedback (r/adapt-react-class rn/TouchableNativeFeedback))
(def touchable-opacity (r/adapt-react-class rn/TouchableOpacity))
(def touchable-without-feedback (r/adapt-react-class rn/TouchableWithoutFeedback))
(def view (r/adapt-react-class rn/View))
(def virtualized-list (r/adapt-react-class rn/VirtualizedList))
(def virtualized-section-list (r/adapt-react-class rn/VirtualizedSectionList))

;; [#js "Animated" "Appearance" "AppRegistry" "AppState" "AsyncStorage" "BackHandler" "Clipboard" "DeviceInfo" "DevSettings" "Dimensions" "Easing" "findNodeHandle" "I18nManager" "InteractionManager" "Keyboard" "LayoutAnimation" "Linking" "LogBox" "NativeDialogManagerAndroid" "NativeEventEmitter" "Networking" "PanResponder" "PermissionsAndroid" "PixelRatio" "PushNotificationIOS" "Settings" "Share" "StatusBarIOS" "StyleSheet" "Systrace" "ToastAndroid" "TurboModuleRegistry" "TVEventHandler" "UIManager" ]